- Dockerfile
The principle of using least privilege should be followed when executing code within containers. Specifically, not running as root.
The Dockerfile has been changed:
* cURL should not be installed as it increases the attack surface of the container
* Create a dedicated non-root user account for executing the Java code
* The existing `ENTRYPOINT` command was poorly-formed:
- The use of `sh -c` does not pass Unix signals to the Java process
- When using the _exec_ form of `ENTRYPOINT` each argument should be its own array element
- The `JAVA_OPTS` environment variable is Tomcat-specific and may be omitted. A separate PR linked below addresses passing options to the JVM via the standard `JAVA_TOOL_OPTIONS` environment variable
I tested this change by creating a differently tagged Docker image …
> Execute the RH service under a dedicated non-root user account

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/RHSvcApplication.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/domain/CaseEvent.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/domain/model/CaseEvent.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/message/CaseEvent.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/message/CaseEventReceiver.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/message/RespondentEventPublisher.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/CaseEventReceiverImpl.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/RespondentEventPublisherImpl.java
- src/main/resources/application.yml
- src/main/resources/springintegration/broker.xml
- src/main/resources/springintegration/case-gateway-event-inbound.xml
- src/main/resources/springintegration/flows.xml
- src/main/resources/springintegration/main.xml
- src/main/resources/springintegration/respondent-service-event-outbound.xml
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/RespondentDataEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/SmokeTest.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/CaseEventReceiverConfiguration.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/CaseEventReceiverImplTest.java
- src/test/resources/caseEventReceiverImpl.properties
- src/test/resources/caseEventReceiverImpl.xml
Add template queue functionality for integration of RH service with RM via event messages. Details of integration and message composition to be designed but template functionality added.
Exchanges, bindings and queues created and functionality to receive on queue Case.Gateway and publish on queue Respondent.Event added. Dead Letter Queues created and retry and exponential back off policy for publishes implemented. 
Using RabbitMQ management console publish JSON message to case-outbound-exchange with binding Case.Gateway.binding. Valid JSON will be received and published to the Respondent.Event queue to increase the count of messages in this queue. Invalid JSON will be sent to the Case.GatewayDLQ. You can also run the CaseEventReceiverImplTest Unit Test for the incoming flow.
> Cdtt 472 add rh service queues

- src/main/java/uk/gov/ons/ctp/integration/rhsvc/cloud/GCSDataStore.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/CaseEventReceiverImplIT_Test.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/UacEventReceiverImplIT_Test.java
IT tests for rabbit message receipt were not making any assertions after the message correctly delivered into the java receiver class, but it was then storing into GCS, the auth for which is problematic in travis. The IT tests now mock the receiver itself, avoiding the un-asserted use of GCS
> IT tests now mock receiver and its use of GCS

- README.md
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/cloud/GCSDataStore.java
- src/main/resources/application-cloud.yaml
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/main/resources/springintegration/broker.xml
- src/main/resources/springintegration/case-gateway-event-inbound.xml
- src/main/resources/springintegration/uac-gateway-event-inbound.xml
Receives CaseCreated and CaseUpdated type messages and deserialises them into relevant Java objects (CaseEvent objects) and then stores them, as JSON, in a bucket, named [your-project-name]-case, within the Google Cloud Platform. Also receives UACUpdated type messages and deserialises them into UACEvent objects and then stores them, as JSON, in a bucket (named [your-project-name]-uac) within the Google Cloud Platform.
Since the original pull request was made on this branch (for the above required functionality) the only further changes in this request are as follows:
- the readme has been updated to include an instruction to create the environment variable named GOOGLE_CLOUD_PROJECT.
- the direct exchanges, defined in broker.xml, have been replaced with topic exchanges as per the guidance …
> Cr 118 receive case events from rm - more changes after feedback from first pull request

- src/main/resources/application.yml
- src/main/resources/springintegration/broker.xml
- src/main/resources/springintegration/case-event-inbound.xml
- src/main/resources/springintegration/response-authentication-outbound.xml
- src/main/resources/springintegration/uac-event-inbound.xml
Tidy exchanges, queues and bindings for RH service trying to avoid conflicts with RM services.
Broker.xml changed. New idea of alternate exchange introduced for messages which the broker cannot route.
Test as described in previous [Pull Request 14](https://github.com/ONSdigital/census-rh-service/pull/14). Using RabbitMQ management console by publishing with invalid routing you can test the message ends in the AlternateQueue. By corrupting the JSON message sent you can test the message ends in the relevant dead letter queue.
> CR-198 Correct RH queue config

- README.md
- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/FulfilmentsEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/RespondentHomeEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/FulfilmentsService.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/FulfilmentsServiceImpl.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/FulfilmentsEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/FulfilmentsServiceImplTest.java
This change adds a fulfilments endpoint to RH. It basically does a search of ProductReference and returns the results. 
New endpoint added in FulfilmentsEndpoint.java and the code to call ProductReference is in FulfilmentsServiceImpl.java
Corresponding tests have been added.
Run all tests or manually send in a http request:
```
$ http GET "http://localhost:8071/fulfilments?caseType=HI&region=E&deliveryChannel=SMS"
$ http GET "http://localhost:8071/fulfilments?caseType=HI"
```
See CR: https://collaborate2.ons.gov.uk/jira/browse/CR-273
> Cr273 add fulfilments endpoint

- src/main/resources/application.yml
- src/main/resources/springintegration/case-event-inbound.xml
- src/main/resources/springintegration/uac-event-inbound.xml
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/EventReceiverConfiguration.java
This change stops RH from starting if a mismatch is detected between the actual and the desired queue configuration.
Such a change prevents the problems described in CR-500, in which RH initially runs but will become progressively more zombied with each Rabbit stop/start cycle.
- Config updated.
- Unused config deleted.
- Unit tests fixed to get them running again.
See: https://collaborate2.ons.gov.uk/jira/browse/CR-500#
> Cr 500 rabbit failures on restart

- README.md
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/UniqueAccessCodeEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/representation/UniqueAccessCodeDTO.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/UniqueAccessCodeService.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/UniqueAccessCodeEndpointTest.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.java
- src/test/resources/uk/gov/ons/ctp/integration/rhsvc/endpoint/UniqueAccessCodeEndpointTest.UniqueAccessCodeDTO.json
- src/test/resources/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.UAC.json
The endpoint receiving requests for UAC details has been changed to use a hash of the UAC as a path parameter rather than the UAC itself. The functionality to hash a UAC has been removed as this is now done by the client.
UniqueAccessCodeEndpoint and underlying service changed to use hash of UAC as path parameter in request. 
Unit tests altered to reflect change. Running the application as normal will work as before with a valid UAC.
Note, must be released with [related RH UI PR](https://github.com/ONSdigital/census-rh-ui/pull/55)
> CR-494 UAC request from RHUI now hashed

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/representation/UniqueAccessCodeDTO.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/UacEventReceiverImplUnit_Test.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.java
- src/test/resources/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.UAC.json
A new field, formType has been added to UAC events. This change accommodates the new field when inbound, and ensures it is included on responses from the Unique Access Code endpoint.
The new field has been added to a fixture used for tests, and to the DTO being sent back to the UI. Existing unit tests have been extended to cover this field.
The UI suite will verify.
[This PR](https://github.com/ONSdigital/census-int-event-publisher/pull/20) is related as it provides the field in the relevant event type.
> Adding support for the formType field on UAC events

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/representation/UniqueAccessCodeDTO.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/UniqueAccessCodeEndpointTest.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/CaseEventReceiverImplIT_Test.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/repository/impl/RespondentDataRepositoryIT_Test.java
- src/test/resources/uk/gov/ons/ctp/integration/rhsvc/endpoint/UniqueAccessCodeEndpointTest.UniqueAccessCodeDTO.json
A new field on certain events is being added by RM
The UniqueAccessCodeDTO and attendant services have had the field added
Unit tests have been modified to ensure the new field is both present and perpetuated.
The new field will ultimately be surfaced in the RH UI.
> Adding support for handDelivery to cases

- src/main/java/uk/gov/ons/ctp/integration/rhsvc/RHSvcApplication.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/config/AppConfig.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/config/QueueConfig.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/event/impl/CaseEventReceiverImpl.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/event/impl/UACEventReceiverImpl.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/SurveyLaunchedServiceImpl.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/RespondentHomeFixture.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/CaseEventReceiverImplIT_Test.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/EventReceiverConfiguration.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/UacEventReceiverImplIT_Test.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/UacEventReceiverImplUnit_Test.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/repository/impl/RespondentDataRepositoryIT_Test.java
QID's will be generated for continuation forms in RM and these will come across in the UACUpdated Event and they need to be filtered out as they won't ever be used for the online collection.
They won't contain attributes such as form type etc so we won't be able to store them etc.
All QID's that start 11,12, 13 & 14 are to be filtered.
* The QID prefixes for filtering are in application.yml.
* The code accepting the UAC looks for the questionnaire prefix and filters based on that.
* Unit tests are updated to test, including a using realistic fixture values, based on WhiteLodge values in firestore.
* Cucumber tests have been altered in a different PR to choose a non-filtered QID
* EventGenerator has been altered in a different PR to choose a non-filtered QID
> CR-785. Filter QID prefixes 11-14

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/event/impl/UACEventReceiverImpl.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/repository/impl/RetryableRespondentDataRepository.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/UacEventReceiverImplIT_Test.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/UacEventReceiverImplUnit_Test.java
Tests to show that RH service can now accept UAC_CREATED event type and handle in the same way as UAC_UPDATED.
Relies on previously merged CR-871 change in event-publisher.
> Cr 871 add uac created event

- pom.xml
- src/main/resources/application.yml
Due to a serious threading bug with Jetty RHSVC has been switched from Jetty to Undertow.
We considered using Tomcat but Undertow was able to service more requests from the same hardware so we went with that.
Pom updated to use undertow, and corresponding Undertow thread configuration added to the application.yml file.
This should be a purely internal change.
> Cr 875 switch to undertow and set thread counts

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/CaseEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/FulfilmentsEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/SurveyLaunchedEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/UniqueAccessCodeEndpoint.java
This PR is for the addition of debug logging in the RH service.
It aims to help address the RHSVC scalability problems by providing data on: 
- Total transaction time
- Firestore request times
- Rabbit event publishing times
> CR-929 Added debug logging to reveal crude timings

- src/main/resources/application.yml
Some Spring boot properties have gone out of date, as spotted by @philwhiles  .
This updates those properties, in particular the undertow and graceful shutdown properties (which sneakily changed between Spring Boot 2.3.0-RC1 and 2.3.0-RELEASE1).
I have retested graceful shudown in the performance environment and things perform as expected; actually with fewer retries at the RHUI end. So this is an improvement.
> CR-991 update/correct out-of-date spring boot properties

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.java
- src/test/resources/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.UAC.unlinkedCE.json
Use FormType "C" instead of "CE1".
Also corrected some javadoc using outdated confluence URL.
> Cr 1044 form type c

- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.java
This change prevents a UAC from being linked to a case that it's already linked to. 
No events are now sent in this scenario.
> CR-1035 Returning from an attempt to link UAC to existing case

- src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/WebformEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/repository/RespondentDataRepository.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/repository/impl/RespondentDataRepositoryImpl.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/representation/WebformDTO.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/representation/WebformPersistedDTO.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/WebformService.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/WebformServiceImpl.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/WebformEndpointTest.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/WebformServiceImplTest.java
- src/test/resources/uk/gov/ons/ctp/integration/rhsvc/endpoint/WebformEndpointTest.WebformDTO.json
- src/test/resources/uk/gov/ons/ctp/integration/rhsvc/service/impl/WebformServiceImplTest.WebformDTO.json
This change adds a new endpoint of '/webform' which saves data into a new Firestore collection. 
A subsequent CR will read from the collection and send out an email.
> Cr 696 add webform endpoint

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImpl.java
Just a pom update, (and also removed a line to fit in with the latest FulfilmentRequest model object, which removed the address element many weeks ago for another JIRA).
Ensure the latest version of event publisher is used, so there is no chance that out-of-date event structures are stored in firestore.
> Cr 1065 play firestore events

- pom.xml
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImplTest.java
The EstabType has been update in census-int-common-service. A new version of census-int-common-service has been released which is 0.0.66. Updating pom.xml to point to this new version.
Also some tests have been updated as they were using the EstabTypes which do not exist anymore after the update to the EstabType enum.
For more details on the changes in census-int-common-service please have a look at https://collaborate2.ons.gov.uk/jira/browse/CR-1208.
> CR-1208 | Pointing to the new release version of census-int-common-service

- src/main/resources/application-testing.yml
- src/main/resources/logback.xml
Stop the CLOUD logback configuration from omitting logging entries, particularly from the firestore retry logic.
> CR-1247 modify cloud logback config so it doesn't omit log entries

- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImpl.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/ServiceUtil.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImplTest.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/TestUtil.java
The address level for the new cases within in the CaseServiceImpl was set after the case was sent to RM and Firestore which was causing this issue.
The bug has been fixed and the unit tests have been updated accordingly.
Please see https://collaborate2.ons.gov.uk/jira/browse/CR-1240 for more details
> CR-1240 | Fixing the  missing address level bug

- src/main/java/uk/gov/ons/ctp/integration/rhsvc/config/InboundEventIntegrationConfig.java
Fix bug introduced in CR-1190.  
We need to ignore the Rabbit event MessageProperties, in particular the __TYPE__ header.
> CR-1306 ignore RM message properties when processing events

- src/main/java/uk/gov/ons/ctp/integration/rhsvc/RHSvcApplication.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImplFulfilmentTest.java
The envoy-rate-limiter provides value-add functionality, however it is more important to function normally if the rate-limiter service has a problem than to fail the normal business function (which it does at present). This PR makes RHSvc tolerate a failing rate-limiter process.
- A circuit-breaker is added around the call to the rate-limiter client
- Any exception other than caused by an HTTP 429 is logged , but ignored
- RH Cucumber tests will now still operate successfully if the rate-limiter is not operational
- unit tests added to cover the functionality
- run RH cucumber with and without rate-limiter present - they work either way
- ensure error logging correctly recorded when rate-limiter not responding
> Cr 1365 tolerate rate limiter failure

- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.java
Simple change to stop the linking of a HH UAC to a CE case.
Removal of invalid combination from LinkingCombination enumeration of valid combinations.
Relevant unit test amended for now invalid combination. Duplicate testing of some combinations also removed. 
Has also been run against census-rh-cucumber to ensure has not caused any tests to fail.
Have also tested that UI displays the correct page on receipt of the HTTP Bad Request response for this now invalid combination.
https://collaborate2.ons.gov.uk/jira/browse/CR-1332
> CR-1332 Restrict linking of HH UAC to CE address

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/config/AppConfig.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/config/LoadsheddingConfig.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/representation/SurveyLaunchedDTO.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/SurveyLaunchedServiceImpl.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/SurveyLaunchedEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/SurveyLaunchedServiceImplTest.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/WebformServiceImplTest.java
- src/test/resources/uk/gov/ons/ctp/integration/rhsvc/endpoint/SurveyLaunchedEndpointUnitTest.SurveyLaunchedDTO.json
CR-1459 describes the requirement for Rate limiting our calls to EQ launcher via the RHSvc endpoint survey-launched call.
- now relies on updated rate-limiter-client , as in PR https://github.com/ONSdigital/census-int-rate-limiter-client/pull/9
- adds `clientIp` to survey launched DTO
- adds a "load shedding modulus" configuration (which must be > 0) to send to the rate limiting client when survery launched event is sent.
- unit tests updated as per usual
CR-1509 RHUI changes have already been merged, so RHUI is ready to fit with this change.
- configure RH DEV envoy rate limiter to manageable rates for the EQLAUNCH for all modulus values.
- deploy RHSvc to DEV, switch to envoy rate limiter , rather than mock.
- go to RHUI in DEV, use a valid UAC and try to launch EQ several times until …
> Cr 1459 rate limit eq launch

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/RHSvcApplication.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/config/Logging.java
- src/main/resources/application.yml
CR-1540 describes a need to encrypt the telephone number logged when rate limiting a fulfilment.
The rate-limiter code has now been changed, to RHSvc must be adapted to provide the password for encryption.
- password configured in the logging in application.yml
- rate limiter client constructed with password
- start RHSvc
- trigger the fulfilment endpoint, either via RHUI or curl or somesuch
- observe logging of rate limiter entry.
https://collaborate2.ons.gov.uk/jira/browse/CR-1540
> Cr 1540 encrypt phone number

- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/ServiceUtil.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImplTest.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.java
- src/test/resources/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.CaseRequestDTO.CEAddress.json
- src/test/resources/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.CaseRequestDTO.SPGAddress.json
- src/test/resources/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.CaseRequestDTO.householdAddress.json
RM fails when receiving  NEW_ADDRESS_REPORTED when the estabType is not one of the proper upper case codes.
Before this PR we are mapping things straight from AIMS which sometimes has estabType as camel-case , eg "Household" instead of "HOUSEHOLD"
- Ensure estabType is mapped to proper code
https://collaborate2.ons.gov.uk/jira/browse/CR-1692
> CR-1692 make sure EstabType has known code for published event

- src/main/java/uk/gov/ons/ctp/integration/rhsvc/repository/RespondentDataRepository.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/repository/impl/RespondentDataRepositoryImpl.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImpl.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImpl.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/WebformServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/repository/impl/RespondentDataRepositoryImplTest.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImplTest.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.java
Fixes a bug where HI cases are returned when create case is called from RHUI.
This is a priority Production bug.
create case will search in firestore for the latest by UPRN, but will not return HI cases.
https://collaborate2.ons.gov.uk/jira/browse/CR-1749
> Cr 1749 dont return hi for create case

- src/main/java/uk/gov/ons/ctp/integration/rhsvc/RHSvcBeanMapper.java
- src/main/java/uk/gov/ons/ctp/integration/rhsvc/representation/CaseDTO.java
- src/test/java/uk/gov/ons/ctp/integration/rhsvc/RHSvcBeanMapperTest.java
- src/test/resources/uk/gov/ons/ctp/integration/rhsvc/RHSvcBeanMapperTest.CollectionCase.json
CR-1818 requires UI changes to handle NA addressType - this requires using RH case data for address checking and thus we need EstabType added to CaseDTO to provide the RHUI with required information.
- CaseDTO now carries EstabType
- mapper converts EstabType from that found in firestore
- similar logic to that from CR-1827 for CCSvc when when we don't know estabType, we can infer something from CaseType.
https://collaborate2.ons.gov.uk/jira/browse/CR-1818
See also https://collaborate2.ons.gov.uk/jira/browse/CR-1827
> Cr 1818 add estab type to case dto

- pom.xml
Gov Notify dependency now available from Maven central.
The GOV.UK Notify java client is now available from Maven central. There is no longer a need to set up the separate BinTray repository. The groupId and artifactId are unchanged and as the service has now a very short life expectancy there seems no reason to take any associated risk in moving to a later client version. I have therefore left the present version, which is available in Maven central.
Note, we are not changing the notification client code, just the repository from where it will be fetched.
Run the build. If you have run it previously the client version will be available in your local repository anyway. If not, or you remove your local version, if you have your Maven settings correct it should fetch the client from our …
> CR-1853 Notify dependency
