src/main/java/uk/gov/ons/ctp/integration/rhsvc/cloud/GCSDataStore.java

formatting

---

src/main/java/uk/gov/ons/ctp/integration/rhsvc/cloud/GCSDataStore.java

fussy f.... formatter

---

src/main/java/uk/gov/ons/ctp/integration/rhsvc/cloud/GCSDataStore.java

reverted gcs auth

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/rhsvc/RHSvcApplication.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/event/impl/CaseEventReceiverImpl.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/event/impl/UACEventReceiverImpl.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/RespondentHomeServiceImpl.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/CaseEventReceiverImplIT_Test.java
src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/CaseEventReceiverImplUnit_Test.java
src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/UacEventReceiverImplIT_Test.java
src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/UacEventReceiverImplUnit_Test.java
src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/RespondentHomeServiceImplTest.java
src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.java

Event publisher re factor

---

src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/CaseEventReceiverImplIT_Test.java
src/test/java/uk/gov/ons/ctp/integration/rhsvc/message/impl/UacEventReceiverImplIT_Test.java

This change extends the unit tests to prove that milliseconds are optional for uac and case events. 
Addition of tests which supply events whose dataTime does not specify milliseconds.
Run all tests
See: https://collaborate2.ons.gov.uk/jira/browse/CR-450

CR-450 Extended unit tests to supply events without millis

---

pom.xml

This pull request includes 2 changes:
- CR-550 to reduce the amount of chatter in logs. Reduces validation failures from error to warn level.
- CR-541 Product reference. Removed large print questionnaire.

Cr 550 reduce log level for validation failures

---

src/main/java/uk/gov/ons/ctp/integration/rhsvc/representation/Constants.java
src/test/resources/uk/gov/ons/ctp/integration/rhsvc/endpoint/CaseEndpointUnitTest.SMSFulfilmentRequestDTO.json

CR-684 telephone regex changed

---

README.md
src/main/java/uk/gov/ons/ctp/integration/rhsvc/cloud/FirestoreDataStore.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/config/RhRetryListener.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/event/impl/CaseEventReceiverImpl.java
src/test/java/uk/gov/ons/ctp/integration/rhsvc/cloud/FirestoreDataStoreTest.java

Fix the Firestore retry code. It was not correctly spotting a Firestore contention exception.

Cr 442 performance testing

---

pom.xml

updated to use product lib 1.0.3

CR-749 product ref update

---

pom.xml
src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/FulfilmentsServiceImplTest.java

pom change prod lib to 1.0.4
tested with latest ui and cut in dev

CR-904 products lib updated to business version 2.3

---

pom.xml

Move to Product release v2.5.
Cucumber tests run in Dev.
Product Reference: https://github.com/ONSdigital/census-int-product-reference/pull/11

CR-1013 Products release v2.5

---

pom.xml

Just a pom update for latest event-publisher objects as done in CR-973.
Will need a corresponding update to RH cucumber , so they should go in tandem.

Cr 973 put case endpoint

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/CaseEndpoint.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/UniqueAccessCodeEndpoint.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/WebformEndpoint.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/event/impl/CaseEventReceiverImpl.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/event/impl/UACEventReceiverImpl.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImpl.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImpl.java

1) Logging levels have been updated to align with the RestExceptionHandler and as appropriate
2) Logging changes made which would help to create dashboards for errors/warnings in gcp

CR-1258 logging

---

src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/FulfilmentsEndpoint.java

Tiny change to extend a log statement, so that it logs fulfilment codes to help with debugging.

CR-1317 Added some debugging to show the returned fulfilment codes

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/CaseEndpoint.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/CaseEndpointUnitTest.java

1. Updating logging to be helpful for creation dashboard in GCP
2. Updating dependencies version

Cr 1258 | logging improvements and dependencies version update

---

src/main/java/uk/gov/ons/ctp/integration/rhsvc/RHSvcBeanMapper.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/representation/UniqueAccessCodeDTO.java
src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/UniqueAccessCodeServiceImplTest.java

Expose EstabType for endpoint /uacs/{uacHash}
https://collaborate2.ons.gov.uk/jira/browse/CR-1325

CR-1325 Exposed EstabType

---

pom.xml

CR-1267 | updated dependency versions

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImpl.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/WebformServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImplFulfilmentTest.java
src/test/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/WebformServiceImplTest.java

This change adds a rate limit check for webform requests.

Cr 1434 webform rate limit checks

---

src/main/java/uk/gov/ons/ctp/integration/rhsvc/RHSvcApplication.java
src/main/java/uk/gov/ons/ctp/integration/rhsvc/config/MessagingConfig.java
src/main/resources/application.yml

Retry added to rabbit send.
Configured number of attempts

Cr 1612 retry rabbit send

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/rhsvc/RHSvcApplication.java
src/main/resources/application.yml

CR-1627 Using new config for http connection pooling

---

src/main/java/uk/gov/ons/ctp/integration/rhsvc/endpoint/CaseEndpoint.java

Just logging the DTO on fulfilment for post endpoint entry.    Very small change.
Example JSON log entry pasted into the JIRA.
https://collaborate2.ons.gov.uk/jira/browse/CR-1743

CR-1743 log request body for postal fulfilment
